system:
  env : "dev"
  port : ":8000"
  domain: "mall"
mysql:
  dns : "root:root@tcp(127.0.0.1:3306)/go_mall?charset=utf8mb4&parseTime=True&loc=Local"
email:
  address: http://localhost:8080/#/vaild/email/
  smtpHost:
  smtpEmail:
  smtpPass:
encryptSecret:
  jwtSecret: "jwtSecret"
  emailSecret: "EmailSecret"
  phoneSecret: "PhoneSecret"
oss:
  AccessKeyId:
  AccessKeySecret:
  BucketName:
  QiNiuServer:
